# Intended for local/development use
# For production reference: https://content.nuxt.com/docs/deploy/docker#with-nodejs-image

FROM node:22-alpine

USER root

RUN apk add --no-cache git openssh libc6-compat bash shadow

RUN chsh -s /bin/bash node

USER node

COPY --chown=node:node .devcontainer/.bashrc /home/node/.bashrc

RUN git config --global --add safe.directory /workspace

WORKDIR /workspace

EXPOSE 3000

CMD ["bash"]
